(ns motive.letter-names)

(def c 0)
(def d 2)
(def e 4)
(def f 5)
(def g 7)
(def a 9)
(def b 11)

(def c-sharp (+ 1 0))
(def d-sharp (+ 1 2))
(def e-sharp (+ 1 4))
(def f-sharp (+ 1 5))
(def g-sharp (+ 1 7))
(def a-sharp (+ 1 9))
(def b-sharp (+ 1 11))

(def c-flat (- 0 1))
(def d-flat (- 2 1))
(def e-flat (- 4 1))
(def f-flat (- 5 1))
(def g-flat (- 7 1))
(def a-flat (- 9 1))
(def b-flat (- 11 1))
